#!/usr/bin/env python2

from gevent import monkey
monkey.patch_all()

from datetime import datetime
#from multiprocessing import Process
from threading import Thread

from flask import Flask, render_template
from flask.ext.socketio import SocketIO, emit


app         = Flask(__name__)
app.debug   = True # False
app.config['SECRET_KEY'] = 'eicu5jichab5aQuooshohrahghaekajaekahgayaequ0Aix7IHaigh3auphaeCh5'
sio         = SocketIO(app)

connection  = None

def fics():
    from time import sleep
    while 1:
        sio.emit('message', {'data':'hi'})

@app.route('/')
def index():
    global connection
    if connection is None:
        connection = Thread(target=fics)
        connection.start()
    return render_template('home.html')

@sio.on('joined')
def test_message(message):
    #emit('message', {'data' : 'welcome!'})
    emit('message', {'data':'connected: ' + str(datetime.now())})

@sio.on('command')
def handle_client_command(command):
    print 'got a client command', command['data']


if __name__ == '__main__':
    sio.run(app)
    #connection.join()
