#!/usr/bin/env python2

from gevent import monkey; monkey.patch_all()

from bobby import app, sio


if __name__ == '__main__':
    try:
        sio.run(app)
    except KeyboardInterrupt:
        pass
    print 'joining command queue'
    app.command_queue.join()
