#!/usr/bin/env python2

from gevent import monkey; monkey.patch_all()

from bobby import app, sio


if __name__ == '__main__':
    try:
        sio.run(app)
        # app.command_queue.join()
    except KeyboardInterrupt:
        print 'quitting'
        pass
